### PR TITLE
Consistent use of foreign CCM conf in aii-shellfe

### LINKED ISSUE #122: json_typed aiiserver
AII is unaware of `json_typed` setting. The `ccm.cfg` is hardcoded in `aii-shellfe` and used like that with `Fetch`; but it and is not passed on to the `CacheManager` setting, which reads the machine `/etc/ccm.cfg` and can misinterpret data.

needs some CCM changes which will be in 15.6, and some small modification in AII itself.

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #122

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha Do not merge. This requires a CCM that is coming from https://github.com/quattor/CCM/pull/58 (should be in 15.6).

**Comment by jrha** [comment]
@stdweird can this be merged now that quattor/CCM#58 is merged, or do we need an RC first?

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@jrha https://github.com/quattor/CCM/pull/58 is not merged, merely closed to reopened (hopefully next week)
hmm, tests pass due to lack of tests of the new feature.

**Comment by jrha** [comment]
Sorry, my mistake!

**Comment by jrha** [comment]
@stdweird, as quattor/CCM#61 was the replacement for quattor/CCM#58 and is now merged are we good to go? Do we need more tests?

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha i just reran the tests, should be ok now

**Pull request merged**
