### PR TITLE
Shellfe: report all perl warnings

### LINKED ISSUE #220: aii-shellfe should intercept perl warnings
Similar to and as simple as https://github.com/quattor/ncm-ncd/commit/853f34f727d49d3590f4b2103c0c0d34ea4d0aad
Not really a blocker for https://github.com/quattor/release/issues/266

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #220

### CODE REVIEW

**Comment by jouvin** [comment]
LGTM

**Comment by ned21** [comment]
Should we defer this to 16.12?

**Comment by jouvin** [comment]
Why?

**Comment by ned21** [comment]
#220 is described as not a blocker for release so I think it's too late for 16.10? Either way, we'll let @jrha decide. :)

**Comment by jrha** [comment]
Tested? Any side effects?

**Comment by stdweird** [comment]
tested, side effects are that youhave to look in the log files for any perl warings, instead of being able to ignore them from stdout :smile:

**Pull request merged**
