### PR TITLE
Shellfe: profileinfo from dir using dir:// cdburl

### PR DESCRIPTION
**Pull request by stdweird**
Allows to use `aii-shellfe` without (or with outdated) `profiles-info.xml`.
Depends on #186

### CODE REVIEW

**Comment by jrha** [comment]
Can you explain why we would want to support this in the description please?

**Comment by stdweird** [comment]
@jrha done

**Comment by jrha** [comment]
Thanks, #172 was closed, so does this depend on anything anymore?

**Comment by stdweird** [comment]
@jrha a rebase, donig right now

**Comment by stdweird** [comment]
@jrha #172 was closed, not merged. i'll update the comment and rebase on correct branch

**Pull request closed without merging**
