### PR TITLE
Bump build-tools to 1.54

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
smooth!

**Comment by jouvin** [comment]
It seems that 1.54 is not yet available... I think we have to wait a little bit, isn't it?

**Comment by stdweird** [comment]
@jouvin yes, this is in preparation of https://github.com/quattor/maven-tools/pull/160 being reviewed/merged and new release is out.
but i'm already testing the repos, to see how much work is needed.

**Comment by jrha** [comment]
@hpcugentbot retest this please

**Comment by jrha** [comment]
🍵

**Pull request merged**
