### PR TITLE
aii-pxelinux: substitute LOCALHOST on profile append

### PR DESCRIPTION
**Pull request by ajf8**
We do this for the kickstart URL but it can be useful for parameters
specified in templates using "append" from the profile.

### CODE REVIEW

**Comment by ajf8** [comment]
Any idea why this might be on the builder?

not ok 1 - use NCM::Component::pxelinux;
Stacktrace

(proc): exec(/usr/sbin/selinuxenabled): No such file or directory
[VERB] Log options --verbose

**Comment by stdweird** [comment]
@ajf8 hmm, why don't you set the corect value in the profile directly?
if you want to keep this "feature", we need documnetation and unittests to make sure noone removes this in the future.

**Comment by ned21** [comment]
I assume this is because we have up to 4 boot servers running AII so we need a template to allow the current boot server to insert the correct (current) hostname?

**Comment by stdweird** [comment]
@ned21 after readong the code, it's already used before (alothough alos not documented/tested?) i was confused with `LOCALHOST`, should have been `AIISERVER` to make it clearer.

**Comment by stdweird** [comment]
@ajf8 thx!

**Pull request merged**
