### PR TITLE
aii-ks: Add disk size check

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
Requires https://github.com/quattor/maven-tools/pull/37 and https://github.com/quattor/ncm-lib-blockdevices/pull/40
Also requires that the `ncm-lib-blockdevice` modules are in `PERL5LIB` for testing

**Comment by stdweird** [comment]
pushed a commit to wrong branch

**Comment by stdweird** [comment]
retest this please

**Comment by jrha** [comment]
Something needs bumping on the Jenkins server?

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
i had to adapt a jenkins build to install `ncm-lib-blockdevices` proeprly
now it fails with an error i don't have on my system, but @jouvin already saw. will fix soonish

**Comment by stdweird** [comment]
@jrha requires https://github.com/quattor/ncm-lib-blockdevices/pull/46

**Comment by jouvin** [comment]
test please

**Comment by jouvin** [comment]
ok to test

**Comment by jouvin** [comment]
Is the following message expected;

```
"my" variable $msg masks earlier declaration in same scope at /exp/si/jouvin/GitRepositories/Quattor/aii/aii-ks/target/dependency/build-scripts/Test/Quattor/Object.pm line 98
```

It seems to appear in a number of place... Something wrong in the last version of the build tools?

**Comment by stdweird** [comment]
@jouvin https://github.com/quattor/maven-tools/pull/51

**Comment by stdweird** [comment]
this will keep failing until the github timeouts are gone, so https://jenkins1.ugent.be/view/Quattor/job/ncm-lib-blockdevices/ can run (and install the updated ncm-lib-blockdevices for jenkins)

**Comment by stdweird** [comment]
test this please

**Pull request merged**
